---
# tasks file for roles/docker-network
- name: Create DB <-> BACKEND network
  community.docker.docker_network:
    name: db-back-network
  vars:
    ansible_python_interpreter: /usr/bin/python3

- name: Create BACKEND <-> Frontend network
  community.docker.docker_network:
    name: back-front-network
  vars:
    ansible_python_interpreter: /usr/bin/python3

- name: Create RP <-> Frontend network
  community.docker.docker_network:
    name: rp-front-network
  vars:
    ansible_python_interpreter: /usr/bin/python3
