name: Ansible deployment
on:
  workflow_run:
    workflows:
      - CD devops 2024
    types:
      - completed
    branches:
      - main

jobs:
  run-ansible:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2.5.0

      - name: Set up Python 2.10
        uses: actions/setup-python@v1
        with:
          python-version: 2.10

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ansible==2.10.7 requests

      - name: Set Ansible config secrets
        env:
          RSA_KEY: ${{ secrets.RSA_KEY }}
        run: |
          # echo "$RSA_KEY" > .ansible-vault-password
          mkdir -p ~/.ssh
          echo "$RSA_KEY" > ~/.ssh/id_rsa_takima
          chmod 600 ~/.ssh/id_rsa_takima

      - name: run exporters playbook
        run: |
          ls -lart ~/.ssh
          cat ~/.ssh/id_rsa_takima
          ansible-playbook -vvvvvv -i ansible/inventories/setup.yml ansible/playbook.yml

      # - name: Run Ansible playbook
      #   uses: isweluiz/ansible-in-docker-action@1.0.0
      #   with:
      #     playbookName: ansible/playbook.yml
      #     inventoryFile: ansible/inventories/setup.yml
      #     keyFile: id_rsa_takima
      #     verbosity: vvv

      # - name: Run Ansible playbook
      #   uses: dawidd6/action-ansible-playbook@v2.8.0
      #   with:
      #     # Required, playbook filepath
      #     playbook: ansible/playbook.yml
      #     # Optional, directory where playbooks live
      #     directory: ansible
      #     key: "${{ secrets.RSA_KEY }}"
      #     options: |
      #       -i inventories/setup.yml
