name: Ansible deployment
on:
  workflow_run:
    workflows:
      - CD devops 2024
    types:
      - completed
    branches:
      - main

jobs:
  run-ansible:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2.5.0

      - name: Install dependencies
        run: |
          python --version
          python -m pip install --upgrade pip
          pip install ansible==2.10.7 requests

      - name: Set Ansible config secrets
        run: |
          # echo "$RSA_KEY" > .ansible-vault-password
          mkdir -p ~/.ssh
          echo "${{ secrets.RSA_KEY }}" > ~/.ssh/id_rsa_takima
          chmod 600 ~/.ssh/id_rsa_takima

      - name: run exporters playbook
        run: |
          export ANSIBLE_HOST_KEY_CHECKING=False
          export POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
          ansible-playbook -i ansible/inventories/setup.yml ansible/playbook.yml
