name: CD devops 2024
on:
  workflow_run:
    workflows:
      - CI devops 2024
    types:
      - completed
    branches:
      - main

jobs:
  build-and-push-docker-image:
    # run only when code is compiling and tests are passing
    runs-on: ubuntu-22.04

    # steps to perform in job
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.5.0

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build image and push backend
        uses: docker/build-push-action@v3
        with:
          # relative path to the place where source code with Dockerfile is located
          context: ./backend-api
          # Note: tags has to be all lower-case
          tags: ${{secrets.DOCKER_USERNAME}}/tp1-back:latest
          push: true

      - name: Build image and push database
        uses: docker/build-push-action@v3
        with:
          # relative path to the place where source code with Dockerfile is located
          context: ./db
          # Note: tags has to be all lower-case
          tags: ${{secrets.DOCKER_USERNAME}}/tp1-db:latest
          push: true

      - name: Build image and push httpd
        uses: docker/build-push-action@v3
        with:
          # relative path to the place where source code with Dockerfile is located
          context: ./reverse-proxy
          # Note: tags has to be all lower-case
          tags: ${{secrets.DOCKER_USERNAME}}/tp1-rp:latest
          push: true

      - name: Build image and push httpd
        uses: docker/build-push-action@v3
        with:
          # relative path to the place where source code with Dockerfile is located
          context: ./frontend
          # Note: tags has to be all lower-case
          tags: ${{secrets.DOCKER_USERNAME}}/tp1-front:latest
          push: true
  
  # deploy-with-ansible:
  #   needs: build-and-push-docker-image
  #   runs-on: ubuntu-22.04

  #   steps:
  #     - name: Prepare private key
  #       run: |
  #         echo "${{ secrets.RSA_KEY }}" > ~/.ssh/id_rsa_takima

  #     - name: Run Ansible playbook
  #       uses: dawidd6/action-ansible-playbook@v2.8.0
  #       with:
  #         # Required, playbook filepath
  #         playbook: ansible/playbook.yml
  #         # Optional, directory where playbooks live
  #         directory: ansible
