name: CD devops 2024
on:
  #to begin you want to launch this job in main and develop
  workflow_run:
    workflows:
      - CI devops 2024
    types:
      - completed

jobs:
  build-and-push-docker-image:
    # run only when code is compiling and tests are passing
    runs-on: ubuntu-22.04

    # steps to perform in job
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.5.0

      - name: Login to DockerHub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build image and push backend
        uses: docker/build-push-action@v3
        with:
          # relative path to the place where source code with Dockerfile is located
          context: ./backend-api
          # Note: tags has to be all lower-case
          tags: ${{secrets.DOCKER_USERNAME}}/tp1-back:latest

      - name: Build image and push database
        uses: docker/build-push-action@v3
        with:
          # relative path to the place where source code with Dockerfile is located
          context: ./db
          # Note: tags has to be all lower-case
          tags: ${{secrets.DOCKER_USERNAME}}/tp1-db:latest

      - name: Build image and push httpd
        uses: docker/build-push-action@v3
        with:
          # relative path to the place where source code with Dockerfile is located
          context: ./frontend
          # Note: tags has to be all lower-case
          tags: ${{secrets.DOCKER_USERNAME}}/tp1-front:latest
