name: CI devops 2024
on: 
  push:
    branches:
      - main
      - develop

jobs:
  test-and-verify-backend:
    runs-on: ubuntu-22.04
    steps:
      # checkout your github code using actions/checkout@v2.5.0
      - uses: actions/checkout@v2.5.0

      # do the same with another action (actions/setup-java@v3) that enable to setup jdk 17
      - name: Set up JDK 17
        # Use the GH action template to setup the JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "adopt"

      #### CONFIGURATION BY SONAR ####
      - name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      #### ENF OF CONFIGURATION BY SONAR ####

      #finally build your app with the latest command
      - name: Build and test with Maven
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          mvn -B clean verify --file backend-api/pom.xml org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=bastiansmn_fac-devops

